### ISSUE TITLE
自动触发Travis Build

### ISSUE THREAD

**Issue by DarienRaymond** [v2ray/homebrew-v2ray#1]
看起来这个tap已经可以由travis-ci来更新了。我可以在v2ray-core的repo中加一些东西来自动触发这个repo的build，大概有两种方式：

1. 你使用一个类似ifttt的工具，接收webhook请求，然后触发一个新的travis build。然后我使用github提供的webhook机制来通知你。
2. 我在release脚本中加一些内容，主动触发你的travis build。这种方式需要你提供travis的api token。

你觉得如何？

感谢你对Project V的支持和帮助。

**Comment by Doublemine** [comment]
@DarienRaymond 很高兴能够为Project V提供力所能及的帮助，目前这个travis的构建是daily模式的，如果可以的话我觉得将这个project transfer到v2ray organization中交给社区维护或许会更好,当然我也很乐意提供travis的api token.

**Comment by DarienRaymond** [comment]
我对homebrew不熟。它的配置文件，比如Formula/v2ray-core.rb是需要单独放一个repo的吗？还是随便放在一个repo的任意位置都可以？

**Comment by Doublemine** [comment]
repo的名字需要特别限定，但具体的配置文件貌似没有特别明显的限定，这个我没有测试过。。。

此外，很乐意加入org并提供力所能及的帮助。
DarienRaymond <notifications@github.com>于2018年3月2日 周五18:08写道：

**Comment by DarienRaymond** [comment]
感谢。原先的travis项目应该已经失效了，稍微我会配置自动更新。
