### ISSUE TITLE
Wrong hash with 4.20.0

### ISSUE THREAD

**Issue by nyacat** [v2ray/homebrew-v2ray#19]
Seems v4.20.0 have wrong hash via the commit, I don't know why change the hash.
but I'm using wget download direct form github,the sha256 sum was

> 18629a1453c504a954c3aa0f25f219c92a56cb54b3353411360bb5a59707edf7

but the package said 

> e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

**Comment by Doublemine** [comment]
It's seem that [travis cron job](https://travis-ci.org/v2ray/homebrew-v2ray/builds/578426819) download file failed cause hash error.  fixed it by restart job manually.
