### ISSUE TITLE
Incorrect url in v2ray-core.rb

### ISSUE THREAD

**Issue by atjason** [v2ray/homebrew-v2ray#20]
Open [https://github.com/v2ray/homebrew-v2ray/blob/master/Formula/v2ray-core.rb](https://github.com/v2ray/homebrew-v2ray/blob/master/Formula/v2ray-core.rb)

The `ttps` should be `https`:
`version "ttps://api.github.com/repos/v2ray/v2ray-core/releases/22545481"`

**Comment by kslr** [comment]
As a pre release, you can actually wait for the update

**Comment by Doublemine** [comment]
Fixed by [9f0e420](https://github.com/v2ray/homebrew-v2ray/commit/9f0e4206e286db9269ff4172bf6396912882d8cd)
