### ISSUE TITLE
Todo 移动至 V2Fly

### ISSUE THREAD

**Issue by kslr** [v2ray/homebrew-v2ray#26]

**Comment by kslr** [comment]
准备方案

**Comment by gMan1990** [comment]
借楼问下: 用`brew services run v2ray-core`且配置文件里没`"log"`，有日志输出吗？是输出到哪里？

update: 由此( https://github.com/Homebrew/homebrew-services/issues/94 )解决

**Comment by kslr** [comment]
应该是 stdout

**Comment by gMan1990** [comment]
@kslr `brew services run v2ray-core`是后台运行的，所以想问下日志在哪

**Comment by kslr** [comment]
你可以看下 brew 的配置
