### ISSUE TITLE
`brew services start v2ray-core` failed.

### ISSUE THREAD

**Issue by jinmiaoluo** [v2ray/homebrew-v2ray#35]
The geoip.dat file and geosite.dat file should be placed in the `bin` folder, otherwise `brew services start v2ray-core` will fail.

version: 4.33.0
current path of `geoip.dat` file and `geosite.dat` file: `/usr/local/Cellar/v2ray-core/4.33.0/share/`
correct path of `geoip.dat` file and `geosite.dat` file: `/usr/local/Cellar/v2ray-core/4.33.0/bin/`

**Comment by kslr** [comment]
brew install v2ray
