### ISSUE TITLE
是否可以发布到 homebrew-core ？

### ISSUE THREAD

**Issue by kehao95** [v2ray/homebrew-v2ray#7]
不是很熟悉homebrew 看到了这个PR https://github.com/Homebrew/homebrew-core/pull/15844 之前被拒了，不知有没有可能直接发布至homebrew-core?

**Comment by Doublemine** [comment]
目前没有这个计划。发布到homebrew-core需要使用源码编译分发的方式，改动比较大。如果你有兴趣的话，欢迎提交PR。
