### ISSUE TITLE
please keep this version up with the core version

### ISSUE THREAD

**Issue by leewi9** [v2ray/homebrew-v2ray#8]
The core version is 3.32 now, but this is still 3.31

**Comment by Doublemine** [comment]
Current version is [v3.32](https://github.com/v2ray/homebrew-v2ray/blob/1c07cfcb90d428bdd4d0a6662865304b66ab0e39/Formula/v2ray-core.rb#L9), maybe you can try `brew upgrade v2ray-core` to upgrade version.
